### ISSUE TITLE
inscription

### ISSUE THREAD

**Issue by moussadiallo** [mobilesenegal/andando#5]
Pour le moment la photo de profil est obligatoire lors de l'inscription. La plupart des users disent que c'est un peu contraignant et sont retissant à uploader leur vraie photo. Peut-être mettre en place un système à l'instar de gmail qui, s'il n'y a pas de photo de profil, met à la place les initiales du user ?

**Comment by scharffc** [comment]
Pourquoi ne pas faire choisir un avatar aux utilisateurs? Il y aurait une liste de photos (peut etre le logo en differentes couleurs). Ils peuvent soit selectionner qq chose qui est fournit ou mettre leur photo reelle. 

Prenez note de cela pour les questions qui vous seront posees sur la securite.

**Comment by moussadiallo** [comment]
En plus du choix d'une photo, une liste d'avatar est désormais disponible lors de l'inscription ou lors de la modification du profil.
Mise à jour uploader le 4 Avril 2016
